### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by samaust** [samaust/OpenTridi#1]
This issue explains the project roadmap.

Tasks
- [ ] Release first version with fixed position.
- [ ] Add support for dynamic position using Vive Tracker. Do not support head rotation.
- [ ] Add support for dynamic position using Vive Tracker. Add support for head rotation.
